services:
  tts01:
    build:
      context: .
      dockerfile: Dockerfile
    image: linyq1/edge-tts:latest
    container_name: "tts01"
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp:/tts/tmp
    networks:
      network-tts:
        ipv4_address: 121.213.0.11

  nginx:
    image: nginx:latest
    hostname: nginx_tts
    container_name: nginx_tts
    restart: always
    ports:
      - '28080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      network-tts:
        ipv4_address: 121.213.0.30

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      network-tts:
        ipv4_address: 121.213.0.32

networks:
  network-tts:
    ipam:
      driver: default
      config:
        - subnet: 121.213.0.0/16
