services:
  tts01:
    build:
      context: .
      dockerfile: Dockerfile
    image: linyq1/edge-tts:latest
    container_name: "tts01"
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp:/tts/tmp
    networks:
      network-tts:
        ipv4_address: 121.213.0.11

  tts02:
    image: linyq1/edge-tts:latest
    container_name: "tts02"
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp:/tts/tmp
    privileged: true
    networks:
      network-tts:
        ipv4_address: 121.213.0.12

  tts03:
    image: linyq1/edge-tts:latest
    container_name: "tts03"
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp:/tts/tmp
    privileged: true
    networks:
      network-tts:
        ipv4_address: 121.213.0.13

  tts04:
    image: linyq1/edge-tts:latest
    container_name: "tts04"
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp:/tts/tmp
    privileged: true
    networks:
      network-tts:
        ipv4_address: 121.213.0.14

  tts05:
    image: linyq1/edge-tts:latest
    container_name: "tts05"
    restart: always
    env_file:
      - .env
    volumes:
      - ./tmp:/tts/tmp
    privileged: true
    networks:
      network-tts:
        ipv4_address: 121.213.0.15

#  tts06:
#    image: linyq1/edge-tts:latest
#    container_name: "tts06"
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./tmp:/tts/tmp
#    privileged: true
#    networks:
#      network-tts:
#        ipv4_address: 121.213.0.16

#  tts07:
#    image: linyq1/edge-tts:latest
#    container_name: "tts07"
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./tmp:/tts/tmp
#    privileged: true
#    networks:
#      network-tts:
#        ipv4_address: 121.213.0.17

#  tts08:
#    image: linyq1/edge-tts:latest
#    container_name: "tts08"
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./tmp:/tts/tmp
#    privileged: true
#    networks:
#      network-tts:
#        ipv4_address: 121.213.0.18

#  tts09:
#    image: linyq1/edge-tts:latest
#    container_name: "tts09"
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./tmp:/tts/tmp
#    privileged: true
#    networks:
#      network-tts:
#        ipv4_address: 121.213.0.19

#  tts10:
#    image: linyq1/edge-tts:latest
#    container_name: "tts10"
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./tmp:/tts/tmp
#    privileged: true
#    networks:
#      network-tts:
#        ipv4_address: 121.213.0.20

  nginx:
    image: nginx:latest
    hostname: nginx_tts
    container_name: nginx_tts
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      network-tts:
        ipv4_address: 121.213.0.30

#  proxy_pool:
#    image: linyq1/proxy_pool:0.0.1
#    container_name: proxy_pool
#    ports:
#      - "5010:5010"
#    links:
#      - redis
#    restart: always
#    environment:
#      DB_CONN: "redis://@redis:6379/0"
#    networks:
#      network-tts:
#        ipv4_address: 121.213.0.31

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      network-tts:
        ipv4_address: 121.213.0.32

networks:
  network-tts:
    ipam:
      driver: default
      config:
        - subnet: 121.213.0.0/16
